version: "3.8"

services:
    server:
        container_name: server
        image: server
        build:
            context: ./server
            dockerfile: server.dockerfile
        ports:
            - 4000:4000
        environment:
            - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
